import Foundation

// Native iOS audio module (placeholder). Built out post-MVP.
//
// Backs the `fm.chordia/native_audio` MethodChannel. Uses AVAudioEngine/AVPlayer with the audio
// session configured for high-resolution + spatial audio (Dolby Atmos) passthrough, avoiding any
// resampling on the bit-perfect path. Honors HTTP Range for seeking and reports buffer health to
// Dart for adaptive quality.
//
// NOTE: the full iOS project (Runner, Info.plist) is generated by `flutter create .`.
final class NativeAudio {}
