package fm.chordia.mobile

// Native Android audio module (placeholder). Built out post-MVP.
//
// Backs the `fm.chordia/native_audio` MethodChannel. Uses ExoPlayer/Media3 for gapless playback,
// configures the AudioTrack for bit-perfect output where the device/route allows, and enables
// Dolby Atmos / spatial passthrough rather than downmixing. Honors HTTP Range for seeking and
// reports buffer health back to Dart for the adaptive-quality controller.
//
// NOTE: the full Android project (Gradle, manifest) is generated by `flutter create .`.
class NativeAudioPlugin
