// Generates Dart models from the Hub's OpenAPI schema.
//
// The Rust `contracts` crate is the single definition of every wire shape. It already emits
// TypeScript (ts-rs) and an OpenAPI document (utoipa); this reads that document and emits the Dart
// equivalent, so the mobile client inherits the same source of truth instead of hand-maintaining a
// third copy that drifts.
//
// Why not `openapi-generator`: it emits built_value, which drags in build_runner and models the
// two shapes this API leans on badly — epoch-millis integers it wants to turn into DateTime, and
// internally-tagged unions it flattens. A focused emitter is a few hundred lines and gets both
// right.
//
//   dart tool/gen_api.dart                 # regenerate from the vendored spec
//   dart tool/gen_api.dart --check         # fail if the committed output is stale
//   dart tool/gen_api.dart --spec <path>   # re-vendor from a different spec first

import 'dart:convert';
import 'dart:io';

const _vendoredSpec = 'packages/chordia_api/openapi/openapi.json';
const _out = 'packages/chordia_api/lib/src/models.g.dart';

void main(List<String> args) {
  final check = args.contains('--check');
  final specIdx = args.indexOf('--spec');
  if (specIdx >= 0 && specIdx + 1 < args.length) {
    final source = File(args[specIdx + 1]);
    if (!source.existsSync()) {
      stderr.writeln('No spec at ${source.path}');
      exit(2);
    }
    File(_vendoredSpec)
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(source.readAsStringSync());
    stdout.writeln('Vendored ${source.path} -> $_vendoredSpec');
  }

  final specFile = File(_vendoredSpec);
  if (!specFile.existsSync()) {
    stderr.writeln(
      'No vendored spec at $_vendoredSpec.\n'
      'Generate it in the backend repo (cargo test --test openapi_snapshot) and pass it with '
      '--spec ../backend/openapi.json',
    );
    exit(2);
  }

  final spec = jsonDecode(specFile.readAsStringSync()) as Map<String, dynamic>;
  final schemas = (spec['components']['schemas'] as Map)
      .cast<String, dynamic>();

  final generated = _formatDart(_emit(schemas));
  final outFile = File(_out);
  final current = outFile.existsSync() ? outFile.readAsStringSync() : null;

  if (check) {
    if (current != generated) {
      stderr.writeln(
        'Generated models are out of date. Run: dart tool/gen_api.dart',
      );
      exit(1);
    }
    stdout.writeln('Generated models are up to date.');
    return;
  }

  outFile
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(generated);
  stdout.writeln(
    'Wrote $_out (${schemas.length} schemas)'
    '${current == generated ? " — no changes" : ""}.',
  );
}

// ── emission ──────────────────────────────────────────────────────────────────────────────────

String _emit(Map<String, dynamic> schemas) {
  final b = StringBuffer()
    ..writeln('// GENERATED BY tool/gen_api.dart — DO NOT EDIT.')
    ..writeln('//')
    ..writeln(
      '// Source: the Hub\'s OpenAPI document, which utoipa renders from the Rust',
    )
    ..writeln('// `contracts` crate. Regenerate with `dart tool/gen_api.dart`.')
    ..writeln('//')
    ..writeln(
      '// ignore_for_file: unused_element, non_constant_identifier_names, '
      'prefer_const_constructors, unintended_html_in_doc_comment',
    )
    ..writeln()
    ..writeln("import 'json.dart';")
    ..writeln();

  final names = schemas.keys.toList()..sort();

  for (final name in names) {
    final schema = schemas[name] as Map<String, dynamic>;
    // i64 and friends map straight to Dart ints, so they need no declaration of their own.
    if (_isScalarAlias(schema)) continue;

    if (schema['enum'] != null) {
      _emitEnum(b, name, schema);
    } else if (schema['oneOf'] != null) {
      _emitUnion(b, name, schema, schemas);
    } else if (schema['additionalProperties'] != null) {
      continue; // A bare map needs no class; properties referencing it become Map<String, ...>.
    } else {
      _emitClass(b, name, schema, schemas);
    }
  }

  return b.toString();
}

bool _isScalarAlias(Map<String, dynamic> s) =>
    s['properties'] == null &&
    s['enum'] == null &&
    s['oneOf'] == null &&
    s['additionalProperties'] == null;

void _emitEnum(StringBuffer b, String name, Map<String, dynamic> schema) {
  final values = (schema['enum'] as List).cast<String>();
  _doc(b, schema['description'] as String?, '');
  b.writeln('enum $name {');
  for (final v in values) {
    b.writeln("  ${_enumMember(v)}('$v'),");
  }
  b
    ..writeln('  ;')
    ..writeln()
    ..writeln('  const $name(this.wire);')
    ..writeln()
    ..writeln('  /// The string this value takes on the wire.')
    ..writeln('  final String wire;')
    ..writeln()
    ..writeln('  static $name? tryFromWire(Object? value) {')
    ..writeln('    for (final v in values) {')
    ..writeln('      if (v.wire == value) return v;')
    ..writeln('    }')
    ..writeln('    return null;')
    ..writeln('  }')
    ..writeln()
    ..writeln(
      '  /// Falls back to [${_enumMember(values.first)}] for a value this build does not know,',
    )
    ..writeln(
      '  /// so a server that gains a variant does not crash an older client.',
    )
    ..writeln('  static $name fromWire(Object? value) =>')
    ..writeln('      tryFromWire(value) ?? ${_enumMember(values.first)};')
    ..writeln('}')
    ..writeln();
}

/// Internally-tagged unions: every variant is an object carrying a single-valued `kind` enum.
void _emitUnion(
  StringBuffer b,
  String name,
  Map<String, dynamic> schema,
  Map<String, dynamic> schemas,
) {
  final variants = (schema['oneOf'] as List).cast<Map<String, dynamic>>();

  // The tag property is whichever one every variant declares as a single-valued string enum.
  // Contracts spell it `kind` in most places and `type` in the room protocol, so it is discovered
  // rather than assumed.
  final tagField = _discoverTagField(name, variants);

  final tagged = <({String tag, Map<String, dynamic> schema})>[];
  for (final v in variants) {
    final props = (v['properties'] as Map?)?.cast<String, dynamic>();
    final tagProp = props?[tagField] as Map<String, dynamic>?;
    final tag = (tagProp?['enum'] as List?)?.first as String?;
    if (tag == null) {
      stderr.writeln(
        'Union $name has a variant with no `$tagField` tag; cannot emit.',
      );
      exit(2);
    }
    tagged.add((tag: tag, schema: v));
  }

  _doc(b, schema['description'] as String?, '');
  b
    ..writeln('sealed class $name {')
    ..writeln('  const $name();')
    ..writeln()
    ..writeln('  /// The `$tagField` this variant carries on the wire.')
    ..writeln('  String get ${_camel(tagField)};')
    ..writeln()
    ..writeln('  static $name fromJson(Map<String, Object?> json) {')
    ..writeln("    switch (json['$tagField']) {");
  for (final v in tagged) {
    b.writeln(
      "      case '${v.tag}': return $name${_pascal(v.tag)}.fromJson(json);",
    );
  }
  b
    ..writeln('      default:')
    ..writeln(
      "        throw FormatException('Unknown $name $tagField: \${json['$tagField']}');",
    )
    ..writeln('    }')
    ..writeln('  }')
    ..writeln()
    ..writeln('  Map<String, Object?> toJson();')
    ..writeln('}')
    ..writeln();

  for (final v in tagged) {
    _emitClass(
      b,
      '$name${_pascal(v.tag)}',
      v.schema,
      schemas,
      extendsType: name,
      tagField: tagField,
      fixedKind: v.tag,
    );
  }
}

void _emitClass(
  StringBuffer b,
  String name,
  Map<String, dynamic> schema,
  Map<String, dynamic> schemas, {
  String? extendsType,
  String? tagField,
  String? fixedKind,
}) {
  final props = ((schema['properties'] as Map?) ?? {}).cast<String, dynamic>();
  final required = ((schema['required'] as List?) ?? []).cast<String>().toSet();

  final fields = <_Field>[];
  for (final entry in props.entries) {
    if (fixedKind != null && entry.key == tagField) continue;
    final p = (entry.value as Map).cast<String, dynamic>();
    final type = _dartType(p, schemas);
    final optional = !required.contains(entry.key) || type.nullable;
    fields.add(
      _Field(
        wire: entry.key,
        dart: _camel(entry.key),
        type: type,
        // A field absent from `required` is optional on the wire; a nullable one may also arrive
        // as an explicit null. Both are `T?` in Dart, which collapses the distinction on purpose:
        // no caller has ever needed to tell "absent" from "null" here.
        nullable: optional,
        doc: p['description'] as String?,
      ),
    );
  }
  fields.sort((a, b) {
    if (a.nullable != b.nullable) return a.nullable ? 1 : -1;
    return a.dart.compareTo(b.dart);
  });

  _doc(b, schema['description'] as String?, '');
  b.writeln(
    'class $name${extendsType != null ? ' extends $extendsType' : ''} {',
  );
  b.write('  const $name(');
  if (fields.isNotEmpty) {
    b.writeln('{');
    for (final f in fields) {
      b.writeln('    ${f.nullable ? '' : 'required '}this.${f.dart},');
    }
    b.write('  }');
  }
  b.writeln(');');
  b.writeln();

  for (final f in fields) {
    _doc(b, f.doc, '  ');
    b.writeln('  final ${f.type.name}${f.nullable ? '?' : ''} ${f.dart};');
  }
  if (fixedKind != null) {
    b
      ..writeln()
      ..writeln('  @override')
      ..writeln("  String get ${_camel(tagField!)} => '$fixedKind';");
  }
  b.writeln();

  // fromJson
  b.writeln('  factory $name.fromJson(Map<String, Object?> json) => $name(');
  for (final f in fields) {
    b.writeln(
      '    ${f.dart}: ${_readExpr("json['${f.wire}']", f.type, f.nullable)},',
    );
  }
  b
    ..writeln('  );')
    ..writeln();

  // toJson
  b.writeln(
    '  ${extendsType != null ? '@override\n  ' : ''}Map<String, Object?> toJson() => {',
  );
  if (fixedKind != null) b.writeln("    '$tagField': '$fixedKind',");
  for (final f in fields) {
    final expr = _writeExpr(f.dart, f.type, f.nullable);
    if (f.nullable) {
      b.writeln("    if (${f.dart} != null) '${f.wire}': $expr,");
    } else {
      b.writeln("    '${f.wire}': $expr,");
    }
  }
  b
    ..writeln('  };')
    ..writeln('}')
    ..writeln();
}

/// Finds the property every variant uses as its discriminator.
String _discoverTagField(String name, List<Map<String, dynamic>> variants) {
  final candidates = <String>{};
  for (final v in variants) {
    final props = ((v['properties'] as Map?) ?? {}).cast<String, dynamic>();
    final here = <String>{};
    for (final e in props.entries) {
      final p = (e.value as Map).cast<String, dynamic>();
      final values = p['enum'] as List?;
      if (p['type'] == 'string' && values != null && values.length == 1) {
        here.add(e.key);
      }
    }
    if (candidates.isEmpty) {
      candidates.addAll(here);
    } else {
      candidates.retainAll(here);
    }
  }
  if (candidates.isEmpty) {
    stderr.writeln(
      'Union $name has no property that every variant tags with; cannot emit.',
    );
    exit(2);
  }
  // `kind` and `type` are the two contracts actually uses; prefer them over an accidental match.
  for (final preferred in const ['kind', 'type']) {
    if (candidates.contains(preferred)) return preferred;
  }
  return (candidates.toList()..sort()).first;
}

// ── types ─────────────────────────────────────────────────────────────────────────────────────

class _DartType {
  const _DartType(this.name, this.kind, {this.nullable = false, this.inner});

  final String name;
  final _Kind kind;
  final bool nullable;
  final _DartType? inner;
}

enum _Kind { scalar, enumType, model, union, list, map, dynamicJson }

class _Field {
  _Field({
    required this.wire,
    required this.dart,
    required this.type,
    required this.nullable,
    this.doc,
  });

  final String wire;
  final String dart;
  final _DartType type;
  final bool nullable;
  final String? doc;
}

_DartType _dartType(Map<String, dynamic> p, Map<String, dynamic> schemas) {
  // `oneOf: [{type: null}, {$ref}]` is how utoipa spells an optional reference.
  if (p['oneOf'] case final List variants) {
    final nonNull = variants
        .cast<Map<String, dynamic>>()
        .where((v) => v['type'] != 'null')
        .toList();
    if (nonNull.length == 1) {
      final t = _dartType(nonNull.single, schemas);
      return _DartType(t.name, t.kind, nullable: true, inner: t.inner);
    }
    return const _DartType('Object', _Kind.dynamicJson, nullable: true);
  }

  if (p[r'$ref'] case final String ref) {
    final target = ref.split('/').last;
    final schema = schemas[target] as Map<String, dynamic>?;
    if (schema == null) return const _DartType('Object', _Kind.dynamicJson);
    if (_isScalarAlias(schema)) return _scalar(schema);
    if (schema['additionalProperties'] != null) {
      return const _DartType('Map<String, Object?>', _Kind.map);
    }
    if (schema['enum'] != null) return _DartType(target, _Kind.enumType);
    if (schema['oneOf'] != null) return _DartType(target, _Kind.union);
    return _DartType(target, _Kind.model);
  }

  var type = p['type'];
  var nullable = false;
  if (type is List) {
    nullable = type.contains('null');
    type = type.firstWhere((t) => t != 'null', orElse: () => 'object');
  }

  switch (type) {
    case 'array':
      final items = ((p['items'] as Map?) ?? {}).cast<String, dynamic>();
      final inner = _dartType(items, schemas);
      return _DartType(
        'List<${inner.name}${inner.nullable ? '?' : ''}>',
        _Kind.list,
        nullable: nullable,
        inner: inner,
      );
    case 'object':
      return _DartType('Map<String, Object?>', _Kind.map, nullable: nullable);
    default:
      final s = _scalar({'type': type, 'format': p['format']});
      return _DartType(s.name, s.kind, nullable: nullable);
  }
}

_DartType _scalar(Map<String, dynamic> s) {
  switch (s['type']) {
    case 'integer':
      // Epoch milliseconds and ids alike arrive as plain integers. Dart's int is 64-bit on every
      // platform this app runs on, so an i64 needs no special handling — but it must never be
      // mapped to DateTime, which would silently reinterpret seconds-vs-millis.
      return const _DartType('int', _Kind.scalar);
    case 'number':
      return const _DartType('double', _Kind.scalar);
    case 'boolean':
      return const _DartType('bool', _Kind.scalar);
    case 'string':
      return const _DartType('String', _Kind.scalar);
    default:
      return const _DartType('Object', _Kind.dynamicJson);
  }
}

String _readExpr(String access, _DartType t, bool nullable) {
  switch (t.kind) {
    case _Kind.scalar:
      final fn = switch (t.name) {
        'int' => 'asInt',
        'double' => 'asDouble',
        'bool' => 'asBool',
        _ => 'asString',
      };
      return nullable ? '$fn${'OrNull'}($access)' : '$fn($access)';
    case _Kind.enumType:
      return nullable
          ? '${t.name}.tryFromWire($access)'
          : '${t.name}.fromWire($access)';
    case _Kind.model:
    case _Kind.union:
      return nullable
          ? '$access == null ? null : ${t.name}.fromJson(asObject($access))'
          : '${t.name}.fromJson(asObject($access))';
    case _Kind.list:
      final inner = t.inner!;
      final each = _readExpr('e', inner, inner.nullable);
      return nullable
          ? 'asListOrNull($access)?.map((e) => $each).toList()'
          : 'asList($access).map((e) => $each).toList()';
    case _Kind.map:
      return nullable ? 'asObjectOrNull($access)' : 'asObject($access)';
    case _Kind.dynamicJson:
      return access;
  }
}

String _writeExpr(String field, _DartType t, bool nullable) {
  final bang = nullable ? '!' : '';
  switch (t.kind) {
    case _Kind.scalar:
    case _Kind.map:
    case _Kind.dynamicJson:
      return field;
    case _Kind.enumType:
      return '$field$bang.wire';
    case _Kind.model:
    case _Kind.union:
      return '$field$bang.toJson()';
    case _Kind.list:
      final inner = t.inner!;
      switch (inner.kind) {
        case _Kind.scalar:
        case _Kind.map:
        case _Kind.dynamicJson:
          return field;
        case _Kind.enumType:
          return '$field$bang.map((e) => e${inner.nullable ? '?' : ''}.wire).toList()';
        case _Kind.model:
        case _Kind.union:
          return '$field$bang.map((e) => e${inner.nullable ? '?' : ''}.toJson()).toList()';
        case _Kind.list:
          return field;
      }
  }
}

// ── naming ────────────────────────────────────────────────────────────────────────────────────

const _dartKeywords = {
  'assert',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'for',
  'if',
  'in',
  'is',
  'new',
  'null',
  'rethrow',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'var',
  'void',
  'while',
  'with',
  'dynamic',
  'implements',
  'import',
  'library',
  'part',
  'show',
  'static',
  'index',
  'values',
  'hashCode',
  'runtimeType',
  'toString',
  'noSuchMethod',
};

String _camel(String wire) {
  final parts = wire
      .split(RegExp(r'[^A-Za-z0-9]+'))
      .where((p) => p.isNotEmpty)
      .toList();
  if (parts.isEmpty) return 'field';
  var id =
      parts.first.toLowerCase() +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
  if (RegExp(r'^[0-9]').hasMatch(id)) id = 'n$id';
  if (_dartKeywords.contains(id)) id = '${id}Value';
  return id;
}

/// PascalCase, without the keyword mangling [_camel] applies — Dart's keywords are all lowercase,
/// so a capitalised identifier can never collide with one.
String _pascal(String wire) {
  final parts = wire.split(RegExp(r'[^A-Za-z0-9]+')).where((p) => p.isNotEmpty);
  final id = parts.map((p) => p[0].toUpperCase() + p.substring(1)).join();
  return RegExp(r'^[0-9]').hasMatch(id) ? 'N$id' : id;
}

String _enumMember(String wire) {
  var id = _camel(wire);
  if (_dartKeywords.contains(id)) id = '${id}Value';
  return id;
}

void _doc(StringBuffer b, String? description, String indent) {
  if (description == null || description.trim().isEmpty) return;
  for (final line in description.trim().split('\n')) {
    b.writeln('$indent/// ${line.trimRight()}');
  }
}

String _formatDart(String source) {
  final tmp = File(
    '${Directory.systemTemp.path}${Platform.pathSeparator}chordia_models_$pid.dart',
  )..writeAsStringSync(source);
  try {
    final r = Process.runSync('dart', ['format', tmp.path], runInShell: true);
    if (r.exitCode != 0) {
      stderr.writeln(
        'dart format failed on the generated models:\n${r.stderr}',
      );
      // Write the unformatted source out so the syntax error is inspectable.
      File('$_out.broken').writeAsStringSync(source);
      exit(2);
    }
    return tmp.readAsStringSync();
  } finally {
    if (tmp.existsSync()) tmp.deleteSync();
  }
}
